package subway.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * create table station (
 *     id bigint generated by default as identity,
 * 	   name varchar(255) not null,
 * 	   primary key (id)
 * )
 */
@Entity
@Table
public class Station {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) // DB의 ID 생성 전략에 의존하는 경우, "쓰기 지연"과 관계 없이 DB에 먼저 저장하게 된다. 만약 직접 만드는 ID를 쓴다면, 쿼리가 지연 발생한다.
	private Long id;

	@Column(nullable = false) // nullable은 DB에 관한 제약이므로, 어플리케이션에 대한 유효성 체크는 따로 해야 한다.
	private String name;

	protected Station() {

	}

	public Station(String name) {
		this.name = name;
	}

	public Long getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void changeName(String name) {
		this.name = name;
	}
}
